[package]
distribution = "2201.12.0"
org = "avi0ra"
name = "huggingface"
version = "0.1.0"
license = ["Apache-2.0"]
authors = ["Hasitha Erandika"]
keywords = ["huggingface", "ai", "llm", "inference", "machine-learning", "nlp"]
#icon = "icon.png" 
repository = "https://github.com/HasithaErandika/module-ballerinax-huggingface"

[build-options]
observabilityIncluded = true

[platform.java21]
graalvmCompatible = true
