// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

import ballerina/data.jsondata;
import ballerina/http;

# API for running machine learning models hosted on the Hugging Face Hub.
public isolated client class Client {
    final http:Client clientEp;
    # Gets invoked to initialize the `connector`.
    #
    # + config - The configurations to be used when initializing the `connector` 
    # + serviceUrl - URL of the target service 
    # + return - An error if connector initialization failed 
    public isolated function init(ConnectionConfig config, string serviceUrl = "https://router.huggingface.co") returns error? {
        http:ClientConfiguration httpClientConfig = {auth: config.auth, httpVersion: config.httpVersion, http1Settings: config.http1Settings, http2Settings: config.http2Settings, timeout: config.timeout, forwarded: config.forwarded, followRedirects: config.followRedirects, poolConfig: config.poolConfig, cache: config.cache, compression: config.compression, circuitBreaker: config.circuitBreaker, retryConfig: config.retryConfig, cookieConfig: config.cookieConfig, responseLimits: config.responseLimits, secureSocket: config.secureSocket, proxy: config.proxy, socketConfig: config.socketConfig, validation: config.validation, laxDataBinding: config.laxDataBinding};
        self.clientEp = check new (serviceUrl, httpClientConfig);
    }

    # Chat Completion
    #
    # + headers - Headers to be sent with the request 
    # + return - Successful chat completion response 
    resource isolated function post v1/chat/completions(ChatCompletionRequest payload, map<string|string[]> headers = {}) returns ChatCompletionResponse|error {
        string resourcePath = string `/v1/chat/completions`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Text Generation
    #
    # + model - The model ID (e.g. "gpt2", "bigscience/bloom")
    # + headers - Headers to be sent with the request 
    # + return - Successful text generation 
    resource isolated function post models/[string model](TextGenerationRequest payload, map<string|string[]> headers = {}) returns TextGenerationResult[]|error {
        string resourcePath = string `/models/${getEncodedUri(model)}`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Text Classification
    #
    # + model - The model ID (e.g. "distilbert-base-uncased-finetuned-sst-2-english")
    # + headers - Headers to be sent with the request 
    # + return - Classification results 
    resource isolated function post models/[string model]/text\-classification(TextClassificationRequest payload, map<string|string[]> headers = {}) returns ClassificationLabel[][]|error {
        string resourcePath = string `/models/${getEncodedUri(model)}/text-classification`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Token Classification (NER)
    #
    # + model - The model ID (e.g. "dbmdz/bert-large-cased-finetuned-conll03-english")
    # + headers - Headers to be sent with the request 
    # + return - Token classification entities 
    resource isolated function post models/[string model]/token\-classification(TokenClassificationRequest payload, map<string|string[]> headers = {}) returns TokenClassificationEntity[]|error {
        string resourcePath = string `/models/${getEncodedUri(model)}/token-classification`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Feature Extraction (Embeddings)
    #
    # + model - The model ID (e.g. "sentence-transformers/all-MiniLM-L6-v2")
    # + headers - Headers to be sent with the request 
    # + return - The embedding vector(s) 
    resource isolated function post models/[string model]/feature\-extraction(FeatureExtractionRequest payload, map<string|string[]> headers = {}) returns float[][]|error {
        string resourcePath = string `/models/${getEncodedUri(model)}/feature-extraction`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Text-to-Image Generation
    #
    # + model - The model ID (e.g. "black-forest-labs/FLUX.1-dev")
    # + headers - Headers to be sent with the request 
    # + return - PNG image bytes 
    resource isolated function post models/[string model]/text\-to\-image(TextToImageRequest payload, map<string|string[]> headers = {}) returns byte[]|error {
        string resourcePath = string `/models/${getEncodedUri(model)}/text-to-image`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Question Answering
    #
    # + model - The model ID (e.g. "deepset/roberta-base-squad2")
    # + headers - Headers to be sent with the request 
    # + return - The answer 
    resource isolated function post models/[string model]/question\-answering(QuestionAnsweringRequest payload, map<string|string[]> headers = {}) returns QuestionAnsweringResponse|error {
        string resourcePath = string `/models/${getEncodedUri(model)}/question-answering`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Text Summarization
    #
    # + model - The model ID (e.g. "facebook/bart-large-cnn")
    # + headers - Headers to be sent with the request 
    # + return - Summarized text 
    resource isolated function post models/[string model]/summarization(SummarizationRequest payload, map<string|string[]> headers = {}) returns SummarizationResult[]|error {
        string resourcePath = string `/models/${getEncodedUri(model)}/summarization`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Text Translation
    #
    # + model - The model ID (e.g. "Helsinki-NLP/opus-mt-en-si")
    # + headers - Headers to be sent with the request 
    # + return - Translated text 
    resource isolated function post models/[string model]/translation(TranslationRequest payload, map<string|string[]> headers = {}) returns TranslationResult[]|error {
        string resourcePath = string `/models/${getEncodedUri(model)}/translation`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Zero-Shot Classification
    #
    # + model - The model ID (e.g. "facebook/bart-large-mnli")
    # + headers - Headers to be sent with the request 
    # + return - Classification scores per label 
    resource isolated function post models/[string model]/zero\-shot\-classification(ZeroShotClassificationRequest payload, map<string|string[]> headers = {}) returns ZeroShotClassificationResponse|error {
        string resourcePath = string `/models/${getEncodedUri(model)}/zero-shot-classification`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Image Classification
    #
    # + model - The model ID (e.g. "google/vit-base-patch16-224")
    # + headers - Headers to be sent with the request 
    # + return - Image classification results 
    resource isolated function post models/[string model]/image\-classification(byte[] payload, map<string|string[]> headers = {}) returns ImageClassificationResult[]|error {
        string resourcePath = string `/models/${getEncodedUri(model)}/image-classification`;
        http:Request request = new;
        request.setPayload(payload, "application/octet-stream");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Automatic Speech Recognition
    #
    # + model - The model ID (e.g. "openai/whisper-large-v3")
    # + headers - Headers to be sent with the request 
    # + return - Transcribed text 
    resource isolated function post models/[string model]/automatic\-speech\-recognition(byte[] payload, map<string|string[]> headers = {}) returns AutomaticSpeechRecognitionResponse|error {
        string resourcePath = string `/models/${getEncodedUri(model)}/automatic-speech-recognition`;
        http:Request request = new;
        request.setPayload(payload, "application/octet-stream");
        return self.clientEp->post(resourcePath, request, headers);
    }
}
