// Copyright (c) 2026, Hasitha Erandika (http://github.com/HasithaErandika).
// Licensed under the Apache License, Version 2.0.

// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

import ballerina/data.jsondata;
import ballerina/http;

# API for running machine learning models hosted on the Hugging Face Hub.
public isolated client class Client {
    final http:Client clientEp;

    # Gets invoked to initialize the `connector`.
    #
    # + config - The configurations to be used when initializing the `connector`
    # + serviceUrl - URL of the target service
    # + return - An error if connector initialization failed
    public isolated function init(ConnectionConfig config, string serviceUrl = "https://router.huggingface.co") returns error? {
        http:ClientConfiguration httpClientConfig = {
            auth: config.auth,
            httpVersion: config.httpVersion,
            http1Settings: config.http1Settings,
            http2Settings: config.http2Settings,
            timeout: config.timeout,
            forwarded: config.forwarded,
            followRedirects: config.followRedirects,
            poolConfig: config.poolConfig,
            cache: config.cache,
            compression: config.compression,
            circuitBreaker: config.circuitBreaker,
            retryConfig: config.retryConfig,
            cookieConfig: config.cookieConfig,
            responseLimits: config.responseLimits,
            secureSocket: config.secureSocket,
            proxy: config.proxy,
            socketConfig: config.socketConfig,
            validation: config.validation,
            laxDataBinding: config.laxDataBinding
        };
        self.clientEp = check new (serviceUrl, httpClientConfig);
    }

    # Chat Completion
    #
    # + payload - Chat completion request body
    # + headers - Headers to be sent with the request
    # + return - Successful chat completion response
    resource isolated function post v1/chat/completions(ChatCompletionRequest payload, map<string|string[]> headers = {}) returns ChatCompletionResponse|error {
        string resourcePath = string `/v1/chat/completions`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Text Generation
    #
    # + model - The model ID (e.g. "gpt2", "bigscience/bloom")
    # + payload - Text generation request body
    # + headers - Headers to be sent with the request
    # + return - Successful text generation
    resource isolated function post hf\-inference/models/[string model](TextGenerationRequest payload, map<string|string[]> headers = {}) returns TextGenerationResult[]|error {
        string resourcePath = string `/hf-inference/models/${getEncodedUri(model)}`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Text Classification
    #
    # + model - The model ID (e.g. "distilbert-base-uncased-finetuned-sst-2-english")
    # + payload - Text classification request body
    # + headers - Headers to be sent with the request
    # + return - Classification results
    resource isolated function post hf\-inference/models/[string model]/text\-classification(TextClassificationRequest payload, map<string|string[]> headers = {}) returns ClassificationLabel[][]|error {
        string resourcePath = string `/hf-inference/models/${getEncodedUri(model)}`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Token Classification (NER)
    #
    # + model - The model ID (e.g. "dbmdz/bert-large-cased-finetuned-conll03-english")
    # + payload - Token classification request body
    # + headers - Headers to be sent with the request
    # + return - Token classification entities
    resource isolated function post hf\-inference/models/[string model]/token\-classification(TokenClassificationRequest payload, map<string|string[]> headers = {}) returns TokenClassificationEntity[]|error {
        string resourcePath = string `/hf-inference/models/${getEncodedUri(model)}`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Feature Extraction (Embeddings)
    #
    # + model - The model ID (e.g. "sentence-transformers/all-MiniLM-L6-v2")
    # + payload - Feature extraction request body
    # + headers - Headers to be sent with the request
    # + return - The embedding vector(s)
    resource isolated function post hf\-inference/models/[string model]/feature\-extraction(FeatureExtractionRequest payload, map<string|string[]> headers = {}) returns float[]|error {
        string resourcePath = string `/hf-inference/models/${getEncodedUri(model)}`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Text-to-Image Generation
    #
    # + model - The model ID (e.g. "stabilityai/stable-diffusion-2-1")
    # + payload - Text to image request body
    # + headers - Headers to be sent with the request
    # + return - PNG image bytes
    resource isolated function post hf\-inference/models/[string model]/text\-to\-image(TextToImageRequest payload, map<string|string[]> headers = {}) returns byte[]|error {
        string resourcePath = string `/hf-inference/models/${getEncodedUri(model)}`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Question Answering
    #
    # + model - The model ID (e.g. "deepset/roberta-base-squad2")
    # + payload - Question answering request body
    # + headers - Headers to be sent with the request
    # + return - The answer
    resource isolated function post hf\-inference/models/[string model]/question\-answering(QuestionAnsweringRequest payload, map<string|string[]> headers = {}) returns QuestionAnsweringResponse|error {
        string resourcePath = string `/hf-inference/models/${getEncodedUri(model)}`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Text Summarization
    #
    # + model - The model ID (e.g. "facebook/bart-large-cnn")
    # + payload - Summarization request body
    # + headers - Headers to be sent with the request
    # + return - Summarized text
    resource isolated function post hf\-inference/models/[string model]/summarization(SummarizationRequest payload, map<string|string[]> headers = {}) returns SummarizationResult[]|error {
        string resourcePath = string `/hf-inference/models/${getEncodedUri(model)}`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Text Translation
    #
    # + model - The model ID (e.g. "Helsinki-NLP/opus-mt-en-fr")
    # + payload - Translation request body
    # + headers - Headers to be sent with the request
    # + return - Translated text
    resource isolated function post hf\-inference/models/[string model]/translation(TranslationRequest payload, map<string|string[]> headers = {}) returns TranslationResult[]|error {
        string resourcePath = string `/hf-inference/models/${getEncodedUri(model)}`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Zero-Shot Classification
    #
    # + model - The model ID (e.g. "facebook/bart-large-mnli")
    # + payload - Zero shot classification request body
    # + headers - Headers to be sent with the request
    # + return - Classification scores per label
    resource isolated function post hf\-inference/models/[string model]/zero\-shot\-classification(ZeroShotClassificationRequest payload, map<string|string[]> headers = {}) returns ZeroShotClassificationResponse|error {
        string resourcePath = string `/hf-inference/models/${getEncodedUri(model)}`;
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Image Classification
    #
    # + model - The model ID (e.g. "google/vit-base-patch16-224")
    # + payload - Raw image bytes
    # + contentType - Image content type: "image/jpeg", "image/png", "image/webp", "image/bmp", "image/gif", "image/tiff"
    # + headers - Headers to be sent with the request
    # + return - Image classification results
    resource isolated function post hf\-inference/models/[string model]/image\-classification(byte[] payload, string contentType = "image/jpeg", map<string|string[]> headers = {}) returns ImageClassificationResult[]|error {
        string resourcePath = string `/hf-inference/models/${getEncodedUri(model)}`;
        http:Request request = new;
        request.setPayload(payload, contentType);
        return self.clientEp->post(resourcePath, request, headers);
    }

    # Automatic Speech Recognition
    #
    # + model - The model ID (e.g. "openai/whisper-small")
    # + payload - Raw audio bytes
    # + contentType - Audio content type: "audio/flac", "audio/wav", "audio/mpeg", "audio/ogg", "audio/webm", "audio/m4a"
    # + headers - Headers to be sent with the request
    # + return - Transcribed text
    resource isolated function post hf\-inference/models/[string model]/automatic\-speech\-recognition(byte[] payload, string contentType = "audio/flac", map<string|string[]> headers = {}) returns AutomaticSpeechRecognitionResponse|error {
        string resourcePath = string `/hf-inference/models/${getEncodedUri(model)}`;
        http:Request request = new;
        request.setPayload(payload, contentType);
        return self.clientEp->post(resourcePath, request, headers);
    }
}