name: Build

on:
  push:
    branches:
      - main
      - 2201.[0-9]+.x
  repository_dispatch:
    types: check_connector_for_breaking_changes
  workflow_dispatch:

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Ballerina
        uses: ballerina-lang/setup-ballerina@v1
        with:
          version: 2201.13.1

      - name: Build
        run: |
          cd ballerina
          bal build

      - name: Run Unit Tests
        run: |
          cd ballerina
          bal test --groups unit

      - name: Run Live Tests
        if: ${{ env.HF_TOKEN != '' }}
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          cd ballerina
          bal test --groups live